name: "🕷️ Bug report"
description: Report errors or unexpected behavior
type: Bug
labels:
- Issue-Bug
- Needs-Triage
body:
- type: textarea
  attributes:
    label: Microsoft PowerToys version
    placeholder: 0.70.0
    description: Hover over system tray icon or look at Settings
  validations:
    required: true
